<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14.0</LangVersion>
        <Version>0.0.1</Version>
        <Description>The Mycelium Fabric MCP project, exposing SysML v2 models to AI assistants.</Description>
        <Company>Starion Group S.A.</Company>
        <Copyright>Copyright © Starion Group S.A.</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/mycelium-cmbse/mycelium-fabric.git</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>
        <Authors>Sam Gerene, Antoine Théate, Régis André, Tanase-Marius Manafu, Omrane Haj Mohamed</Authors>
        <ImplicitUsings>false</ImplicitUsings>
        <Nullable>disable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ErrorOr" Version="2.1.1" />
      <PackageReference Include="ModelContextProtocol" Version="2.2.0" />
      <PackageReference Include="SysML2.NET.Dal" Version="0.24.1" />
      <PackageReference Include="SysML2.NET.Serializer.Json" Version="0.24.1" />
    </ItemGroup>

</Project>